// <auto-generated />
using CosmeticDashboard.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CosmeticDashboard.Migrations
{
    [DbContext(typeof(AspnetDbContext))]
    [Migration("20200925073259_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CosmeticDashboard.Models.Factory", b =>
                {
                    b.Property<int>("FactoryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FactoryName")
                        .HasColumnType("text");

                    b.Property<string>("LocationCode")
                        .HasColumnType("varchar(767)");

                    b.HasKey("FactoryCode");

                    b.HasIndex("LocationCode");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("CosmeticDashboard.Models.KoreaLocation", b =>
                {
                    b.Property<string>("LocationCode")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.HasKey("LocationCode");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CosmeticDashboard.Models.Note", b =>
                {
                    b.Property<int>("NoteNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NoteContents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("NoteNo");

                    b.HasIndex("UserNo");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("CosmeticDashboard.Models.User", b =>
                {
                    b.Property<int>("UserNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isEditable")
                        .HasColumnType("bit");

                    b.HasKey("UserNo");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CosmeticDashboard.Models.Factory", b =>
                {
                    b.HasOne("CosmeticDashboard.Models.KoreaLocation", "KoreaLocation")
                        .WithMany()
                        .HasForeignKey("LocationCode");
                });

            modelBuilder.Entity("CosmeticDashboard.Models.Note", b =>
                {
                    b.HasOne("CosmeticDashboard.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
